### ISSUE TITLE
Javascript Error in Overlay

### ISSUE THREAD

**Issue by Frittenfett** [mithom/streamlabs_chatbot_hangman#2]
My overlay.html is throwing a javascript exception, the overlay does not work due to this error.

I use google chrome Version 67.0.3396.87

Firefox won't trow a exception, but does not render the overlay too. 

`Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at Caman.Root.Caman.Caman.reloadCanvasData (file:///D:/Stream%20Data/Streamlabs%20Chatbot/Services/Scripts/streamlabs_chatbot_hangman-master/overlay/caman.min.js:36:231)
    at Caman.Root.Caman.Caman.finishInit (file:///D:/Stream%20Data/Streamlabs%20Chatbot/Services/Scripts/streamlabs_chatbot_hangman-master/overlay/caman.min.js:35:6)
    at Caman.Root.Caman.Caman.initCanvas (file:///D:/Stream%20Data/Streamlabs%20Chatbot/Services/Scripts/streamlabs_chatbot_hangman-master/overlay/caman.min.js:28:1232)
    at Caman.Root.Caman.Caman.setup (file:///D:/Stream%20Data/Streamlabs%20Chatbot/Services/Scripts/streamlabs_chatbot_hangman-master/overlay/caman.min.js:28:208)
    at Caman.<anonymous> (file:///D:/Stream%20Data/Streamlabs%20Chatbot/Services/Scripts/streamlabs_chatbot_hangman-master/overlay/caman.min.js:19:381)
    at file:///D:/Stream%20Data/Streamlabs%20Chatbot/Services/Scripts/streamlabs_chatbot_hangman-master/overlay/caman.min.js:20:250`

My Hangman Settings:
`{"next_word": "", "guess_command": "!guess", "turn_limit_response": "the word has not been found within the turn limit, the solution was {0}", "last_letter_found_response": "{0} found the last letter {1} of the word {2} and has been rewarded {3} {4} for finishing the word.", "found_letter_response": "{0} found {1}, reward: {2} {3}.", "global_cd": 1, "hangman_color": "rgba(255,255,255,1)", "mix_api_file_word": 100.0, "send_progress_after_guess": true, "start_response": "a game of hangman has been started, start guessing now using {0} (letter)", "word_guess_counts_as_turn": true, "nb_turns": 30.0, "start_game_command": "!startHangman", "ignore_response": "{0}, the letter {1} has already been used", "progress_response": "{0}", "not_show_me": false, "api_key": "", "only_online": true, "min_word_length": 4.0, "start_game_permission": "Moderator", "use_different_guess_command": false, "end_after_x_turns": false, "user_cd": 15, "guess_word_cost": 15, "not_enough_points_response": "{0}, you don't have enough {1}, you need {2} and only have {3}", "use_multiplier": false, "vanish_delay": 10, "ignore_used": false, "max_word_length": 20.0, "max_turns_prefix": "turn {0} / {1} : ", "guess_cost": 5, "found_correct_word_response": "{0} has found the correct word {1} and has been rewarded {2} {3}.", "start_game_info": "", "shown_letters": "-", "guess_word_addition": " and {0}", "auto_delay": 5, "finish_word_reward": 50, "send_response_if_ignored": true, "letter_not_in_word_response": "{0}, {1} is not in the word, cost: {2}, {3}", "currency_name": "fritten", "no_game_running_response": "{0}, there is currently no hangman game running, pls start one using {1}", "file_name": "words.txt", "wrong_word_guess_response": "{0}, the word {1} is incorrect, better luck next time", "guess_word_command": "!guessWord", "send_message_if_not_enough_points": true, "allow_chat_message": false, "guess_vowel_cost": 15, "in_progress_response": "current game is still in progress", "auto_start_game": false, "find_letter_reward": 5}`

**Comment by mithom** [comment]
First of all, i want to excuse me that i only see it now. Secondly i know of the error, but it does work in the chromium version that obs uses. I know why the error is throw and have spent a lot of time to fix it. But i couldn't get it too. Javascript just isnt designed for local hosting. I would need to set up a server with the correct cross origin headers to solve it. And for me it works in the latest version of firefox. Most important is that it works in obs though and it does

**Comment by mithom** [comment]
if you have an idea on how to fix it, make a PR or let me know so i can implement it

**Comment by mithom** [comment]
i am closing this issue as it is irrelevant, the overlay is designed to be used in a browser source in streaming software, not in the broser itself directly. Any suggestion on how to fix this and be less reliable on security issues, are still welcome

**Comment by mithom** [comment]
i am closing this issue as it is irrelevant, the overlay is designed to be used in a browser source in streaming software, not in the broser itself directly. Any suggestion on how to fix this and be less reliable on security issues, are still welcome
