### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by cusmith88** [mithom/streamlabs_chatbot_hangman#3]
I cannot, for the life of me, figure out how to make this work. I have the hangman_StreamlabsSystem.py script along with the overlay.html on disk on my Mac laptop. I have Streamlabs OBS set to have a browser source set to the overlay.html. I've whispered to chatbot on Twitch. I have a Wordnik API key though I understand that's not necessary for basic functionality.

I don't understand the documentation about right-clicking on the script and inserting an API key. Which script and which key?

**Comment by cusmith88** [comment]
I see there are references to API_Key.js and hangmanSettings.js that I don't have, as well. Should I have those and what should they populated with?

**Comment by mithom** [comment]
jey @cusmith88 sorry for the late reaction on your issue. API_Key.js is very easy to resolve, just right click on the script in the script overview screen from chatbot and click on the contextmenu option 'insert API key'

**Comment by mithom** [comment]
the hangmanSettings.js should be made automatically when it doesn't exist. Have you enabled the script to allow the code to run? You can also create this file by pressing the save button in the settings panel, as this file is just the saved data of the parameters in this panel.

**Comment by mithom** [comment]
reading your issue again, i do see i might have misinterpretted your situation. Let's be clear about something, this is NOT a standalone program. it makes use of the streamlabs chatbot script interface, meaning you need to have streamlabs chatbot running on your pc (so not the cloud version) and add this script to the scripts tab of the chatbot.

for now i will close this issue, but feel free to re-open if anything else is unclear.
